/*
** EPITECH PROJECT, 2019
** Babel
** File description:
** Created by abel,
*/

#ifndef BABEL_AUDIOINFO_HPP
#define BABEL_AUDIOINFO_HPP

#define APPLICATION OPUS_APPLICATION_AUDIO
#define FRAMES_PER_BUFFER 480
#define SAMPLE_RATE 48000
#define NUMBER_CHANNELS 2
#define BITRATE 64000

#endif //BABEL_AUDIOINFO_HPP